export const sampleWatches = [
    {
        name: "Enticer Mens",
        model: "MTP-1314D-1AVDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742743238/nestor%20works/watches/casio/Enticer_Gent_s_MTP-1314D-1AVDF_s0bptr.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: ["Date display"],
        weight: "126g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-1314L-7AVDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742743335/nestor%20works/watches/casio/Enticer_Gent_s_MTP-1314L-7AVDF_acqkx1.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: ["Date display"],
        weight: "64g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-1375D-2A2VDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742743740/nestor%20works/watches/casio/ENTICER_MEN_MTP-1375D-2A2VDF_onmipo.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V001G-9BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742743864/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V001G-9BUDF_j9wvww.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "91g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V001GL-1BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742744072/nestor%20works/watches/casio/Enticer_Mens_MTP-V001GL-1BUDF_lcxlx1.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V001GL-7BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742744321/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V001GL-7BUDF_tkh5it.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V001GL-9BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742744957/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V001GL-9BUD_vrkrir.png"],
        dialColor: "Gold",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V001L-1BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742745081/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V001L-1BUDF_pkfqky.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "42g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V001L-7BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742745480/nestor%20works/watches/casio/MTP-V001L-7BUDF_bxayxr.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V002D-1B3UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742745667/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V002D-1B3UDF_sscx1n.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V002 line of Casio dress watches. With the convenient date window at the 3 o’clock position and the classic, one-glance Roman numeral and bar indexes, you?ll be at the right place at the right time. Elegant and versatile, these timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up"
    },
    {
        name: "Enticer Mens",
        model: "MTP-V002D-2B3UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742749139/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V002D-2B3UDF_hcpu5o.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V002 line of Casio dress watches. With the convenient date window at the 3 o’clock position and the classic, one-glance Roman numeral and bar indexes, you?ll be at the right place at the right time. Elegant and versatile, these timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V002D-7B3UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742749278/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V002D-7B3UDF_qnqikq.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V002 line of Casio dress watches. With the convenient date window at the 3 o’clock position and the classic, one-glance Roman numeral and bar indexes, you?ll be at the right place at the right time. Elegant and versatile, these timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V002G-1BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742749604/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V002G-1BUDF_wj9pom.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Casio watches are renowned for their durability, precision, and innovative features, offering a wide range of styles from classic analog designs to advanced digital models. Known for their reliability and affordable prices, Casio timepieces are built to withstand everyday use while providing functionality, whether for sports, outdoor adventures, or everyday wear"
    },
    {
        name: "Enticer Mens",
        model: "MTP-V002G-7B2UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742749713/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V002G-7B2UDF_fawfz1.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V004G-1CUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742749827/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V004G-1CUDF_hhoy5b.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V004L-1CUD",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742749918/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V004L-1CUD_ee2euh.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V005D-1B5UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742750118/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V005D-1B5UDF_vs8vma.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V005 line of Casio dress watches. The simple, clean design of the face makes it easy to be on time. These versatile timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up. Build your own?just choose Arabic or Roman numerals, metal link or leather band, dark or light watch face, and you?ll have a handsome timepiece that projects your personal brand."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V005D-2B5UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742750285/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V005D-2B5UDF_btylpd.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V005 line of Casio dress watches. The simple, clean design of the face makes it easy to be on time. These versatile timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up. Build your own?just choose Arabic or Roman numerals, metal link or leather band, dark or light watch face, and you?ll have a handsome timepiece that projects your personal brand."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V005D-7BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742750471/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V005D-7BUDF_tgkpqd.png"],
        dialColor: "Silver",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V005L-1B5UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742750652/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V005L-1B5UDF_qgnbs0.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V005 line of Casio dress watches. The simple, clean design of the face makes it easy to be on time. These versatile timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up. Build your own?just choose Arabic or Roman numerals, metal link or leather band, dark or light watch face, and you?ll have a handsome timepiece that projects your personal brand."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V005L-1B4UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742750752/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V005L-1B4UDF_by3wue.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V005 line of Casio dress watches. The simple, clean design of the face makes it easy to be on time. These versatile timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up. Build your own?just choose Arabic or Roman numerals, metal link or leather band, dark or light watch face, and you?ll have a handsome timepiece that projects your personal brand."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V005L-2B4UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751004/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V005L-2B4UDF_r4oaqo.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Style yourself for work or play with the MTP-V005 line of Casio dress watches. The simple, clean design of the face makes it easy to be on time. These versatile timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up. Build your own?just choose Arabic or Roman numerals, metal link or leather band, dark or light watch face, and you?ll have a handsome timepiece that projects your personal brand.Style yourself for work or play with the MTP-V005 line of Casio dress watches. The simple, clean design of the face makes it easy to be on time. These versatile timepieces are water resistant for daily use, freeing you from worry when out in the rain or washing up. Build your own?just choose Arabic or Roman numerals, metal link or leather band, dark or light watch face, and you?ll have a handsome timepiece that projects your personal brand."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V006L-1B2UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751122/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V006L-1B2UDF_cikf9q.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V006L-1CUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751215/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V006L-1CUDF_xsxrxd.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V300L-1AUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751330/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V300L-1AUDF_zwtep8.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-V300L-7AUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751413/nestor%20works/watches/casio/Enticer_Gent_s_MTP-V300L-7AUDF_qsidqg.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01D-1BVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751601/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01D-1BVUDF_prvzqs.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Casio watches are renowned for their durability, precision, and innovative features, offering a wide range of styles from classic analog designs to advanced digital models. Known for their reliability and affordable prices, Casio timepieces are built to withstand everyday use while providing functionality, whether for sports, outdoor adventures, or everyday wear"
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01D-1E2VUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751690/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01D-1E2VUDF_e1axu8.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Casio watches are renowned for their durability, precision, and innovative features, offering a wide range of styles from classic analog designs to advanced digital models. Known for their reliability and affordable prices, Casio timepieces are built to withstand everyday use while providing functionality, whether for sports, outdoor adventures, or everyday wear"
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01D-1EVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751814/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01D-1EVUDF_lkw8jf.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Casio watches are renowned for their durability, precision, and innovative features, offering a wide range of styles from classic analog designs to advanced digital models. Known for their reliability and affordable prices, Casio timepieces are built to withstand everyday use while providing functionality, whether for sports, outdoor adventures, or everyday wear"
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01D-2BVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751898/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01D-2BVUDF_x1mkzp.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Casio watches are renowned for their durability, precision, and innovative features, offering a wide range of styles from classic analog designs to advanced digital models. Known for their reliability and affordable prices, Casio timepieces are built to withstand everyday use while providing functionality, whether for sports, outdoor adventures, or everyday wear"
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01D-2EVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742751977/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01D-2EVUDF_vayqhr.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Casio watches are renowned for their durability, precision, and innovative features, offering a wide range of styles from classic analog designs to advanced digital models. Known for their reliability and affordable prices, Casio timepieces are built to withstand everyday use while providing functionality, whether for sports, outdoor adventures, or everyday wear"
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01G-1BVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742752114/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01G-1BVUDF_eyw82k.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "118g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01G-9EVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742752205/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01G-9EVUDF_rrhi1l.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "70g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01GL-1EVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742752378/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01GL-1EVUDF_cqoby8.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "70g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01L-1BVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742752756/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01L-1BVUDF_ckee7p.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01L-1EVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742752841/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01L-1EVUDF_qdixpc.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01L-2BVUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742752929/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01L-2BVUDF_moiye4.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD01SG-1BVUD",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753099/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD01SG-1BVUD_twetzn.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "118g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD03B-2AUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753236/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD03B-2AUDF_kddrwy.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD03D-2A2UD",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753328/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD03D-2A2UD_pltipb.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD03G-1AUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753434/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD03G-1AUDF_j9zlau.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Go simple and stylish with one of these analog timepieces featuring basic hour, minute and second hands. Water resistant for daily use, these watches free you from worry when out in the rain or washing up. The streamlined, versatile design takes you where you want to go, whether on or off the clock."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD03L-5AUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753538/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD03L-5AUDF_unogxs.png"],
        dialColor: "White",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Go simple and stylish with one of these analog timepieces featuring basic hour, minute and second hands. Water resistant for daily use, these watches free you from worry when out in the rain or washing up. The streamlined, versatile design takes you where you want to go, whether on or off the clock."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VD300G-1EUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753625/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VD300G-1EUDF_ljav8n.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01D-1BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753867/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01D-1BUDF_hyzomg.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "88g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01D-2BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742753952/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01D-2BUDF_k2wabk.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "88g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01D-7BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754040/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01D-7BUDF_eojp3a.png"],
        dialColor: "Silver",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "88g",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01G-1B2UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754134/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01G-1B2UDF_rdxw2v.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01G-2BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754328/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01G-2BUDF_kjrwon.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Stainless Steel",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Case / bezel: Gold toneTriple-fold ClaspStainless Steel BandMineral GlassGold ion plated bandGold ion plated caseWater ResistantRegular timekeepingAnalog: 3 hands (hour, minute, second)Accuracy: ?20 seconds per month Approx. battery life: 3 years on SR626SW"
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01GL-1B2UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754429/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01GL-1B2UDF_raiyyv.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01L-1B2UDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754530/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01L-1B2UDF_qvngul.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01L-1BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754732/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01L-1BUDF_nxopz5.png"],
        dialColor: "Black",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
    {
        name: "Enticer Mens",
        model: "MTP-VT01L-2BUDF",
        brand: "Casio",
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742754820/nestor%20works/watches/casio/Enticer_Gent_s_MTP-VT01L-2BUDF_qp4o9m.png"],
        dialColor: "Blue",
        movementType: "Quartz",
        category: "Mens",
        stock: 1, price: 200,
        strapMaterial: "Leather",
        tags: [],
        weight: "",
        createdAt: new Date().toISOString(),
        shortDescription: "Make Everyday Always Attractive with Casio’s Enticer Watches. Suitable for Everyday Casual Living while creating a Stylish Statement. Enticer features a wide range of Casio Analog watches, from sports to fashion line-up every kind of deisgn is available in this series. The enticer collection contains a great collection of unique dial designs as per the needs. Comes in leather, steel, cloth and even resin bands. These watches are made for those who are looking for a timepiece that can be used in every occassion."
    },
];
