export const sampleWatches = [
    {
        name: "Casio G-Shock",
        brand: "Casio",
        model: "GA2100",
        shortDescription: "A tough and stylish digital-analog hybrid watch.",
        price: 120,
        strapMaterial: "Stainless Steel",
        movementType: "Quartz",
        dialColor: "Black",
        stock: 50,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Men's",
        tags: ["Shock Resistant", "Durable"],
        isNewArrival: true,
        createdAt: new Date().toISOString()
    },
    {
        name: "Titan Edge",
        brand: "Titan",
        model: "1595SL01",
        shortDescription: "Ultra-slim dress watch with a sophisticated look.",
        price: 200,
        strapMaterial: "Leather",
        movementType: "Quartz",
        dialColor: "White",
        stock: 30,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Dress",
        tags: ["Ultra Slim", "Classic"],
        isNewArrival: false,
        createdAt: new Date().toISOString()
    },
    {
        name: "Seiko 5 Sports",
        brand: "Seiko",
        model: "SRPD51",
        shortDescription: "A reliable automatic watch with a sporty design.",
        price: 350,
        strapMaterial: "Stainless Steel",
        movementType: "Automatic",
        dialColor: "Blue",
        stock: 20,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Men's",
        tags: ["Sporty", "Reliable"],
        isNewArrival: false,
        createdAt: new Date().toISOString()
    },
    {
        name: "Citizen Eco-Drive",
        brand: "Citizen",
        model: "BM8180-03E",
        shortDescription: "Solar-powered watch with a rugged design.",
        price: 180,
        strapMaterial: "Leather",
        movementType: "Quartz",
        dialColor: "Black",
        stock: 15,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Men's",
        tags: ["Eco-Drive", "Solar Powered"],
        isNewArrival: true,
        createdAt: new Date().toISOString()
    },
    {
        name: "Casio Edifice",
        brand: "Casio",
        model: "EFV100D-1AV",
        shortDescription: "A stylish stainless steel chronograph for professionals.",
        price: 220,
        strapMaterial: "Stainless Steel",
        movementType: "Quartz",
        dialColor: "Black",
        stock: 10,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Dress",
        tags: ["Chronograph", "Professional"],
        isNewArrival: true,
        createdAt: new Date().toISOString()
    },
    {
        name: "Titan Regalia",
        brand: "Titan",
        model: "1734YM01",
        shortDescription: "A royal-looking gold-tone watch for formal wear.",
        price: 250,
        strapMaterial: "Leather",
        movementType: "Automatic",
        dialColor: "Gold",
        stock: 18,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Silver",
        tags: ["Elegant", "Royal"],
        isNewArrival: true,
        createdAt: new Date().toISOString()
    },
    {
        name: "Seiko Presage",
        brand: "Seiko",
        model: "SRPB43",
        shortDescription: "A luxurious automatic watch with a sunburst dial.",
        price: 480,
        strapMaterial: "Leather",
        movementType: "Automatic",
        dialColor: "White",
        stock: 8,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Dress",
        tags: ["Sunburst Dial", "Luxury"],
        isNewArrival: false,
        createdAt: new Date().toISOString()
    },
    {
        name: "Citizen Promaster",
        brand: "Citizen",
        model: "BN0150-28E",
        shortDescription: "A professional diver's watch with Eco-Drive technology.",
        price: 290,
        strapMaterial: "Stainless Steel",
        movementType: "Quartz",
        dialColor: "Blue",
        stock: 12,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Men's",
        tags: ["Diver's Watch", "Eco-Drive"],
        isNewArrival: false,
        createdAt: new Date().toISOString()
    },
    {
        name: "Casio Classic",
        brand: "Casio",
        model: "F91W",
        shortDescription: "A retro-style digital watch with an affordable price.",
        price: 30,
        strapMaterial: "Stainless Steel",
        movementType: "Quartz",
        dialColor: "Black",
        stock: 100,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Men's",
        tags: ["Retro", "Affordable"],
        isNewArrival: false,
        createdAt: new Date().toISOString()
    },
    {
        name: "Titan Karishma",
        brand: "Titan",
        model: "1779SM02",
        shortDescription: "An elegant silver-tone women's watch.",
        price: 120,
        strapMaterial: "Stainless Steel",
        movementType: "Quartz",
        dialColor: "White",
        stock: 25,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Women's",
        tags: ["Elegant", "Silver Tone"],
        isNewArrival: false,
        createdAt: new Date().toISOString()
    },
    {
        name: "Seiko Coutura",
        brand: "Seiko",
        model: "SNE516",
        shortDescription: "A modern quartz watch with a sleek design.",
        price: 400,
        strapMaterial: "Leather",
        movementType: "Quartz",
        dialColor: "Gold",
        stock: 6,
        availability: true,
        images: ["https://res.cloudinary.com/dle7urchd/image/upload/v1742659696/watch_noa0mt.jpg"],
        category: "Dress",
        tags: ["Modern", "Sleek"],
        isNewArrival: true,
        createdAt: new Date().toISOString()
    }
];
